/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./about.html", "./works.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#4a4538",
        "surface-container": "#f0ece4",
        "surface-container-low": "#f5f1ea",
        "on-surface": "#2e3230",
        "surface-container-highest": "#e4e0d8",
        "on-background": "#2e3230",
        surface: "#faf6f0",
        "primary-fixed-dim": "#8ecf9e",
        "tertiary-container": "#c4a66a",
        "on-secondary-container": "#5e5548",
        "surface-container-high": "#eae6de",
        "surface-bright": "#faf6f0",
        "secondary-container": "#f0e8db",
        "error-container": "#ffdad8",
        tertiary: "#705c30",
        "surface-tint": "#4a7c59",
        "inverse-primary": "#8ecf9e",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#d4ccbf",
        "on-tertiary-fixed-variant": "#554020",
        "inverse-surface": "#2e3230",
        error: "#b83230",
        "tertiary-fixed-dim": "#dcc48e",
        "on-primary-fixed-variant": "#2a6038",
        "on-tertiary": "#ffffff",
        "on-error-container": "#690005",
        "primary-container": "#78a886",
        background: "#faf6f0",
        "outline-variant": "#c4c8bc",
        secondary: "#6b6358",
        "on-primary": "#ffffff",
        "primary-fixed": "#c8e8d0",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#221a05",
        outline: "#74796e",
        "on-secondary-fixed": "#1e1a13",
        "on-surface-variant": "#4a4e4a",
        "surface-variant": "#e4e0d8",
        "surface-dim": "#dbd7cf",
        "on-primary-fixed": "#002110",
        "on-primary-container": "#d8f0de",
        "on-tertiary-container": "#554020",
        "inverse-on-surface": "#f5f0e8",
        primary: "#4a7c59",
        "secondary-fixed": "#f0e8db",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#f8e0a8",
      },
      borderRadius: {
        "4xl": "2rem",
      },
      spacing: {
        "2.25": "0.5625rem",
        "35": "8.75rem",
      },
      fontFamily: {
        headline: ["Literata"],
        display: ["Literata"],
        body: ["Nunito Sans"],
        label: ["Nunito Sans"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
